"""empty message

Revision ID: 182c83f90dac
Revises: 
Create Date: 2021-11-23 00:53:25.601491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '182c83f90dac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knot',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('f_name', sa.VARCHAR(length=32), nullable=True),
    sa.Column('s_name', sa.VARCHAR(length=32), nullable=True),
    sa.Column('username', sa.VARCHAR(length=32), nullable=True),
    sa.Column('email', sa.VARCHAR(length=129), nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=15), nullable=True),
    sa.Column('password', sa.VARCHAR(length=256), nullable=True),
    sa.Column('slug', sa.VARCHAR(length=140), nullable=True),
    sa.Column('created', sa.DATETIME(), nullable=True),
    sa.Column('last_login', sa.DATETIME(), nullable=True),
    sa.Column('authenticated', sa.BOOLEAN(), nullable=True),
    sa.Column('auth_key', sa.VARCHAR(length=256), nullable=True),
    sa.Column('auth_key_create', sa.DATETIME(), nullable=True),
    sa.Column('admin', sa.BOOLEAN(), nullable=True),
    sa.CheckConstraint('admin IN (0, 1)'),
    sa.CheckConstraint('authenticated IN (0, 1)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('chat_users',
    sa.Column('chat_id', sa.INTEGER(), nullable=False),
    sa.Column('knot_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.uuid'], ),
    sa.ForeignKeyConstraint(['knot_id'], ['knot.id'], ),
    sa.PrimaryKeyConstraint('chat_id', 'knot_id')
    )
    op.create_table('post_tags',
    sa.Column('post_id', sa.INTEGER(), nullable=False),
    sa.Column('tag_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'tag_id')
    )
    op.create_table('post',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('uuid', sa.VARCHAR(length=140), nullable=True),
    sa.Column('slug', sa.VARCHAR(length=140), nullable=True),
    sa.Column('title', sa.VARCHAR(length=78), nullable=True),
    sa.Column('preview', sa.VARCHAR(length=250), nullable=True),
    sa.Column('body', sa.TEXT(), nullable=True),
    sa.Column('created', sa.DATETIME(), nullable=True),
    sa.Column('author', sa.VARCHAR(length=32), nullable=True),
    sa.Column('visible', sa.BOOLEAN(), nullable=True),
    sa.Column('owner_id', sa.INTEGER(), nullable=True),
    sa.CheckConstraint('visible IN (0, 1)'),
    sa.ForeignKeyConstraint(['owner_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('chat',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('uuid', sa.VARCHAR(length=140), nullable=True),
    sa.Column('created', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=46), nullable=True),
    sa.Column('short_name', sa.VARCHAR(length=46), nullable=True),
    sa.Column('slug', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('short_name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('tag',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=46), nullable=True),
    sa.Column('slug', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('chat_msgs',
    sa.Column('chat_id', sa.INTEGER(), nullable=False),
    sa.Column('message_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.uuid'], ),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], ),
    sa.PrimaryKeyConstraint('chat_id', 'message_id')
    )
    op.create_table('message',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('uuid', sa.VARCHAR(length=140), nullable=True),
    sa.Column('text', sa.VARCHAR(length=5000), nullable=False),
    sa.Column('created', sa.DATETIME(), nullable=True),
    sa.Column('edited', sa.DATETIME(), nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), nullable=True),
    sa.Column('author_username', sa.VARCHAR(length=32), nullable=True),
    sa.CheckConstraint('is_read IN (0, 1)'),
    sa.ForeignKeyConstraint(['author_username'], ['knot.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('uuid', sa.VARCHAR(length=140), nullable=True),
    sa.Column('text', sa.VARCHAR(length=2000), nullable=True),
    sa.Column('slug', sa.VARCHAR(length=140), nullable=True),
    sa.Column('author', sa.VARCHAR(length=32), nullable=True),
    sa.Column('created', sa.DATETIME(), nullable=True),
    sa.Column('edited', sa.DATETIME(), nullable=True),
    sa.Column('owner_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    # ### end Alembic commands ###
