"""empty message

Revision ID: 1e439bf31b4a
Revises: 39cad7c08855
Create Date: 2023-01-16 22:55:25.659003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e439bf31b4a'
down_revision = '39cad7c08855'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_column('uuid')

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint('message_uuid_key', type_='unique')
        batch_op.drop_column('uuid')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint('post_uuid_key', type_='unique')
        batch_op.drop_column('uuid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.VARCHAR(length=140), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('post_uuid_key', ['uuid'])

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.VARCHAR(length=140), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('message_uuid_key', ['uuid'])

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.VARCHAR(length=140), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
