"""empty message

Revision ID: 1ed62bfd0c25
Revises: 4e4edb24e4ab
Create Date: 2020-01-19 18:25:57.076080

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1ed62bfd0c25'
down_revision = '4e4edb24e4ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.drop_constraint('comment_ibfk_1', 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'post', ['owner_id'], ['id'])
    op.drop_column('comment', 'comments_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('comments_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key('comment_ibfk_1', 'comment', 'post', ['comments_id'], ['id'])
    op.drop_column('comment', 'owner_id')
    # ### end Alembic commands ###
