"""empty message

Revision ID: 4e4edb24e4ab
Revises: 925043dfc8fa
Create Date: 2020-01-19 17:31:57.082763

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4e4edb24e4ab'
down_revision = '925043dfc8fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_commets')
    op.add_column('comment', sa.Column('comments_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comment', 'post', ['comments_id'], ['id'])
    op.add_column('knot', sa.Column('created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knot', 'created')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_column('comment', 'comments_id')
    op.create_table('post_commets',
    sa.Column('post_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('comment_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], name='post_commets_ibfk_1'),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name='post_commets_ibfk_2'),
    sa.PrimaryKeyConstraint('post_id', 'comment_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
