"""empty message

Revision ID: 530e5c647af6
Revises: d6b5695993f9
Create Date: 2019-12-14 20:41:18.896475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '530e5c647af6'
down_revision = 'd6b5695993f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('f_name', sa.String(length=32), nullable=True),
    sa.Column('s_name', sa.String(length=32), nullable=True),
    sa.Column('number', sa.String(length=15), nullable=True),
    sa.Column('password', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('knot')
    # ### end Alembic commands ###
