"""empty message

Revision ID: 555f56e1f773
Revises: 0255552bb05a
Create Date: 2023-02-01 12:49:46.541326

"""
from uuid import uuid4
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from models import Knot
# revision identifiers, used by Alembic.
revision = '555f56e1f773'
down_revision = '0255552bb05a'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    session = sa.orm.Session(bind=bind)
    
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False))
    
    for user in session.query(Knot):
        user.uuid = uuid4()

    session.commit()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knot', schema=None) as batch_op:
        batch_op.drop_column('uuid')

    # ### end Alembic commands ###
