"""empty message

Revision ID: 61e3981d19b6
Revises: b6a431f2e29d
Create Date: 2020-01-10 20:20:13.188496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61e3981d19b6'
down_revision = 'b6a431f2e29d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'knot', ['slug'])
    op.add_column('post', sa.Column('uuid', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'tag', ['slug'])
    op.create_unique_constraint(None, 'tag', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tag', type_='unique')
    op.drop_constraint(None, 'tag', type_='unique')
    op.drop_column('post', 'uuid')
    op.drop_constraint(None, 'knot', type_='unique')
    # ### end Alembic commands ###
