"""empty message

Revision ID: 66dbe04651a2
Revises: 1e439bf31b4a
Create Date: 2023-01-16 23:01:50.305053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66dbe04651a2'
down_revision = '1e439bf31b4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_constraint('category_slug_key', type_='unique')
        batch_op.drop_column('slug')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint('comment_slug_key', type_='unique')
        batch_op.drop_column('slug')

    with op.batch_alter_table('knot', schema=None) as batch_op:
        batch_op.drop_constraint('knot_slug_key', type_='unique')
        batch_op.drop_column('slug')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint('post_slug_key', type_='unique')
        batch_op.drop_column('slug')

    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_constraint('tag_slug_key', type_='unique')
        batch_op.drop_column('slug')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('tag_slug_key', ['slug'])

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.VARCHAR(length=140), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('post_slug_key', ['slug'])

    with op.batch_alter_table('knot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.VARCHAR(length=140), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('knot_slug_key', ['slug'])

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.VARCHAR(length=140), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('comment_slug_key', ['slug'])

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('category_slug_key', ['slug'])

    # ### end Alembic commands ###
