"""empty message

Revision ID: 88f04142c4f6
Revises: 76aa47bfeb41
Create Date: 2022-09-01 23:02:22.715159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88f04142c4f6'
down_revision = '76aa47bfeb41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'chat', ['uuid'])
    op.create_unique_constraint(None, 'message', ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message', type_='unique')
    op.drop_constraint(None, 'chat', type_='unique')
    # ### end Alembic commands ###
