"""empty message

Revision ID: 8933e00a86c0
Revises: 44b6b421a226
Create Date: 2023-02-01 17:36:18.384269

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8933e00a86c0'
down_revision = '44b6b421a226'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('uuid',
               existing_type=postgresql.UUID(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('uuid',
               existing_type=postgresql.UUID(),
               nullable=True)

    # ### end Alembic commands ###
