"""empty message

Revision ID: 8c85011c8a6f
Revises: e9c75da0e2a7
Create Date: 2022-11-28 21:23:05.808483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c85011c8a6f'
down_revision = 'e9c75da0e2a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('category_id', sa.Integer(), nullable=False))
    op.drop_constraint('post_owner_id_fkey', 'post', type_='foreignkey')
    op.create_foreign_key(None, 'post', 'category', ['category_id'], ['id'])
    op.drop_column('post', 'owner_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.create_foreign_key('post_owner_id_fkey', 'post', 'category', ['owner_id'], ['id'])
    op.drop_column('post', 'category_id')
    # ### end Alembic commands ###
