"""empty message

Revision ID: 925043dfc8fa
Revises: a96e868861ba
Create Date: 2020-01-19 16:53:16.644042

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '925043dfc8fa'
down_revision = 'a96e868861ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=140), nullable=True),
    sa.Column('text', sa.String(length=2000), nullable=True),
    sa.Column('slug', sa.String(length=140), nullable=True),
    sa.Column('author', sa.String(length=32), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('edited', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('post_commets',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'comment_id')
    )
    op.drop_table('knot_posts')
    op.create_unique_constraint(None, 'post', ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='unique')
    op.create_table('knot_posts',
    sa.Column('knot_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('post_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['knot_id'], ['knot.id'], name='knot_posts_ibfk_1'),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name='knot_posts_ibfk_2'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('post_commets')
    op.drop_table('comment')
    # ### end Alembic commands ###
