"""empty message

Revision ID: 92b348ae5235
Revises: 4dad771f1a87
Create Date: 2019-12-15 16:02:21.971845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92b348ae5235'
down_revision = '4dad771f1a87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knot', sa.Column('username', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knot', 'username')
    # ### end Alembic commands ###
