"""empty message

Revision ID: b014ba5a3e8b
Revises: 555f56e1f773
Create Date: 2023-02-01 13:58:32.547726

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b014ba5a3e8b'
down_revision = '555f56e1f773'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knot', schema=None) as batch_op:
        batch_op.alter_column('uuid',
               existing_type=postgresql.UUID(),
               nullable=False)
        batch_op.create_unique_constraint(None, ['uuid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knot', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('uuid',
               existing_type=postgresql.UUID(),
               nullable=True)

    # ### end Alembic commands ###
