"""empty message

Revision ID: b072f2d496a8
Revises: f1ca53c6f4fd
Create Date: 2022-12-27 12:49:52.316376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b072f2d496a8'
down_revision = 'f1ca53c6f4fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('author_id', sa.Integer(), nullable=True))
    op.add_column('comment', sa.Column('post_id', sa.Integer(), nullable=True))
    op.drop_constraint('comment_owner_id_fkey', 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'post', ['post_id'], ['id'])
    op.create_foreign_key(None, 'comment', 'knot', ['author_id'], ['id'])
    op.drop_column('comment', 'owner_id')
    op.drop_column('comment', 'author')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('author', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.add_column('comment', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key('comment_owner_id_fkey', 'comment', 'post', ['owner_id'], ['id'])
    op.drop_column('comment', 'post_id')
    op.drop_column('comment', 'author_id')
    # ### end Alembic commands ###
