"""empty message
Revision ID: d8cdfd426636
Revises: 67c8796321c3
Create Date: 2022-09-02 00:39:42.321608
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8cdfd426636'
down_revision = '67c8796321c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('knot_phone_number_key', 'knot', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('knot_phone_number_key', 'knot', ['phone_number'])
    # ### end Alembic commands ###
