"""empty message

Revision ID: e9c75da0e2a7
Revises: d8cdfd426636
Create Date: 2022-10-03 01:49:05.206582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9c75da0e2a7'
down_revision = 'd8cdfd426636'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knot', sa.Column('updated', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knot', 'updated')
    # ### end Alembic commands ###
